language: haskell

dist: xenial

apt:
  update: true
  sources:
    - hvr-ghc
  packages: cabal-install-2.2

ghc:
  - 8.0
  - 8.2
  - 8.4
  - 8.6
  - 8.8
  - 8.10

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y  libiw-dev libasound2-dev libxpm-dev libmpd-dev
  - sudo apt-get install -y libxrandr-dev
  - sudo apt-get install -y happy c2hs
  - export PATH=/opt/ghc/bin:$PATH

install:
  - travis_wait 30 cabal install --only-dependencies --enable-tests -fall_extensions
  - wget https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh

script:
  - sh ./travis.sh src
  - cabal configure --enable-tests -fall_extensions && cabal build && cabal test
